/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventarios_cbd;


import Models.Articles;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import net.sourceforge.barbecue.Barcode;
import net.sourceforge.barbecue.BarcodeFactory;
import net.sourceforge.barbecue.BarcodeImageHandler;
import net.sourceforge.barbecue.output.OutputException;
/**
 *
 * @author Sebastian
 */
public class InputArticle extends javax.swing.JInternalFrame {
    
    JSONParser jsonParser;
    private final String LOGIN_URL = "http://dibso.co/api_health_comunication/public/patients";
    private final String TAG_SUCCESS = "success";
    private final String TAG_MESSAGE = "message";
    private final String TAG_DATA = "data";
    private final String TAG_CODE = "code";
    public Articles article = null;
    public Articles sendArticle = null;
    
    /**
     * Creates new form NewArticle
     */
    public InputArticle() {
        initComponents();   
        //Center JinternalFrame (this)
        Dimension deskSize = Principal.dp_principal.getSize();
        Dimension jiSize = this.getSize();
        setLocation((deskSize.width - jiSize.width)/2, (deskSize.height- jiSize.height)/2);
        btn_new_codebar1.setVisible(false);
        jsonParser = new JSONParser();
        setClosable(true); 
        setIconifiable(true); 
        //setMaximizable(true); 
        setResizable(true); 
        
        //generarCode();
        //setImgButtons();
        enabledButtons(false);
        
        /*
       Map<String,Object> map;
        try {
            map = Principal.util.objectToMap(new Articles("hola a es", 2, new Date()));
            for (Map.Entry<String, Object> entry : map.entrySet())
            {
                System.out.println(entry.getKey() + "/" + entry.getValue());
            }
        } catch (Exception ex) {
            Logger.getLogger(InputArticle.class.getName()).log(Level.SEVERE, null, ex);
        }
       */
    }
    
    public void setImgButtons(){
         //btn_save_new_article.setIcon(new ImageIcon(getClass().getResource("../img/ic_done_black_18dp.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_new_name = new javax.swing.JTextField();
        cb_new_unit = new javax.swing.JComboBox<>();
        cb_new_duration = new javax.swing.JComboBox<>();
        txt_new_price = new javax.swing.JTextField();
        txt_new_priceunit = new javax.swing.JTextField();
        txt_new_lot = new javax.swing.JTextField();
        txt_new_invima = new javax.swing.JTextField();
        txt_new_total = new javax.swing.JTextField();
        txt_new_distributor = new javax.swing.JTextField();
        dc_new_expiration_date = new com.toedter.calendar.JDateChooser();
        btn_new_codebar = new javax.swing.JButton();
        btn_new_edit_info = new javax.swing.JButton();
        btn_new_clean_fields = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_new_trademark = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lb_code_img = new javax.swing.JLabel();
        btn_save_img = new javax.swing.JButton();
        btn_print_code = new javax.swing.JButton();
        btn_new_copyimg = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_new_codebar1 = new javax.swing.JButton();
        btn_save_new_article = new javax.swing.JButton();

        setTitle("Nuevo Producto");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Articulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Nombre : ");

        jLabel2.setText("Unidades : ");

        jLabel3.setText("Duración : ");

        jLabel4.setText("Precio : ");

        jLabel5.setText("Precio por unidad :");

        jLabel6.setText("Lote :");

        jLabel7.setText("Registro INVIMA : ");

        jLabel8.setText("Cantidad : ");

        jLabel9.setText("Distribuidor : ");

        jLabel10.setText("Fecha de expiración :");

        txt_new_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_new_nameKeyTyped(evt);
            }
        });

        cb_new_unit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "UNIDADES (und)", "MILILITROS (ml)", "CENTIMETROS (cm3)", "GRAMOS (g)" }));

        cb_new_duration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cb_new_duration.setToolTipText("Meses");

        txt_new_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_new_priceActionPerformed(evt);
            }
        });
        txt_new_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_new_priceKeyTyped(evt);
            }
        });

        txt_new_priceunit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_new_priceunitKeyTyped(evt);
            }
        });

        txt_new_lot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_new_lotKeyTyped(evt);
            }
        });

        txt_new_invima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_new_invimaKeyTyped(evt);
            }
        });

        txt_new_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_new_totalActionPerformed(evt);
            }
        });
        txt_new_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_new_totalKeyTyped(evt);
            }
        });

        txt_new_distributor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_new_distributorKeyTyped(evt);
            }
        });

        btn_new_codebar.setText("Generar Codigo de barras");
        btn_new_codebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_new_codebarActionPerformed(evt);
            }
        });

        btn_new_edit_info.setText("Editar Información");
        btn_new_edit_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_new_edit_infoActionPerformed(evt);
            }
        });

        btn_new_clean_fields.setText("Limpiar");
        btn_new_clean_fields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_new_clean_fieldsActionPerformed(evt);
            }
        });

        jLabel11.setText("Marca :");

        txt_new_trademark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_new_trademarkKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_new_clean_fields)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_new_edit_info)
                        .addGap(30, 30, 30)
                        .addComponent(btn_new_codebar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_new_name))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txt_new_trademark))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(dc_new_expiration_date, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_new_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_new_distributor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_new_invima)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_new_lot, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_new_priceunit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_new_price, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_new_unit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_new_total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_new_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cb_new_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txt_new_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_new_priceunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txt_new_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_new_invima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txt_new_lot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dc_new_expiration_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cb_new_duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_new_distributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_new_trademark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new_codebar)
                    .addComponent(btn_new_edit_info)
                    .addComponent(btn_new_clean_fields))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Codigo de barras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btn_save_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/export/ic_reply_black_18dp.png"))); // NOI18N
        btn_save_img.setToolTipText("Guardar Codigo como imagen");
        btn_save_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_imgActionPerformed(evt);
            }
        });

        btn_print_code.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print/ic_print_black_18dp.png"))); // NOI18N
        btn_print_code.setToolTipText("Imprimir código");
        btn_print_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_print_codeActionPerformed(evt);
            }
        });

        btn_new_copyimg.setForeground(new java.awt.Color(255, 255, 255));
        btn_new_copyimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy/ic_content_copy_black_18dp.png"))); // NOI18N
        btn_new_copyimg.setToolTipText("Copiar Código");
        btn_new_copyimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_new_copyimgActionPerformed(evt);
            }
        });

        jLabel12.setText("Codigo");

        btn_new_codebar1.setText("Generar");
        btn_new_codebar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_new_codebar1ActionPerformed(evt);
            }
        });

        btn_save_new_article.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save/ic_save_black_18dp.png"))); // NOI18N
        btn_save_new_article.setToolTipText("Guardar Información");
        btn_save_new_article.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_new_articleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_code_img, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_save_new_article, javax.swing.GroupLayout.PREFERRED_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(btn_new_copyimg, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_save_img, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_print_code, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_new_codebar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(lb_code_img, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_new_copyimg, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_save_img, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_print_code, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_save_new_article)))
                .addGap(18, 18, 18)
                .addComponent(btn_new_codebar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_save_new_articleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_new_articleActionPerformed
        String name = txt_new_name.getText().toUpperCase();
        String distributor = txt_new_distributor.getText().toUpperCase();
        String invima = txt_new_invima.getText().toUpperCase();
        String lot = txt_new_lot.getText().toUpperCase();
        String price = txt_new_price.getText();
        String price_unit = txt_new_priceunit.getText();
        String cantidad = txt_new_total.getText();
        boolean result = Principal.util.isNullOrEmpty(distributor, invima, lot, name, price, price_unit, cantidad);
        //Validar datos de entrada
        if(result || cb_new_duration.getSelectedItem().equals("---") ||
                cb_new_unit.getSelectedItem().equals("---") || dc_new_expiration_date.getDate() == null){
            JOptionPane.showInternalMessageDialog(this, "Debe lenar todos los campos!");
        }else{
            article =  new Articles(txt_new_name.getText(), Integer.parseInt(cb_new_duration.getSelectedItem().toString()), dc_new_expiration_date.getDate());
            
            Principal.util.sendDataApi(LOGIN_URL, this);//Envia los datos a la api
            
        }
    }//GEN-LAST:event_btn_save_new_articleActionPerformed

    private void btn_new_codebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_new_codebarActionPerformed
        //Principal.dp_principal.add(new NewBarcode()).setVisible(true);
        //String barCode = Principal.util.getIntForCodebar(new Articles("hola a es", 2, new Date()), "3-1");
        //System.out.println(barCode);
        //System.out.println(Principal.util.getIntForCodebar(new Articles("hola a es", 2, new Date()), "3-1"));
        //Principal.dp_principal.add(new NewBarcode(barCode)).setVisible(true);
        String name = txt_new_name.getText().toUpperCase();
        String distributor = txt_new_distributor.getText().toUpperCase();
        String invima = txt_new_invima.getText().toUpperCase();
        String lot = txt_new_lot.getText().toUpperCase();
        String price = txt_new_price.getText();
        String price_unit = txt_new_priceunit.getText();
        String cantidad = txt_new_total.getText();
        String trademark = txt_new_trademark.getText().toUpperCase();
        boolean result = Principal.util.isNullOrEmpty(distributor, invima, lot, name, price, price_unit, cantidad, trademark);
        //Validar datos de entrada
        if(result || cb_new_duration.getSelectedItem().equals("---") ||
                cb_new_unit.getSelectedItem().equals("---") || dc_new_expiration_date.getDate() == null){
            JOptionPane.showInternalMessageDialog(this, "Verifique los campos!");
        }else{
            article =  new Articles(txt_new_name.getText(), Integer.parseInt(cb_new_duration.getSelectedItem().toString()), dc_new_expiration_date.getDate());
            enabledTextFields(false);
            enabledButtons(true);
            generarCode(article);
            
            //Principal.util.sendDataApi(LOGIN_URL, TAG_CODE, this);//Envia los datos a la api
        }
        
    }//GEN-LAST:event_btn_new_codebarActionPerformed

    private void txt_new_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_new_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_new_priceActionPerformed

    private void btn_save_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_imgActionPerformed
        Barcode barcode = null;
        //
        try {
            barcode = BarcodeFactory.createCode128(jTextField1.getText());
        } catch (Exception e) {
        }
        barcode.setDrawingText(true);
        barcode.setBarWidth(2);
        barcode.setBarHeight(60);

        JFileChooser jfc =  new JFileChooser();
        jfc.showSaveDialog(this);
        File file = jfc.getSelectedFile();
        String filename = file.getAbsolutePath();
        FileOutputStream fos = null;
        try {
            fos = new FileOutputStream(filename + ".png");
            BarcodeImageHandler.writePNG(barcode, fos);
            Principal.util.showDialog(this, "La imagen se guardó satisfactoriamente.", "Guardar Imagen", INFORMATION_MESSAGE);
            //BufferedImage img =  new BufferedImage(420, 110, BufferedImage.TYPE_INT_ARGB);
            //Graphics2D g = (Graphics2D) img.getGraphics();
        } catch (FileNotFoundException | OutputException ex) {
            Logger.getLogger(NewBarcode.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                fos.close();
            } catch (IOException ex) {
                Logger.getLogger(NewBarcode.class.getName()).log(Level.SEVERE, null, ex);
            }
        };

    }//GEN-LAST:event_btn_save_imgActionPerformed

    private void btn_print_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_print_codeActionPerformed
        Barcode barcode = null;
        //
        try {
            barcode = BarcodeFactory.createCode128(jTextField1.getText());
        } catch (Exception e) {
        }
        barcode.setDrawingText(true);
        barcode.setBarWidth(2);
        barcode.setBarHeight(60);

        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(barcode);
        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException ex) {
                Logger.getLogger(NewBarcode.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_print_codeActionPerformed

    private void btn_new_copyimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_new_copyimgActionPerformed
        Clipboard cb =  Toolkit.getDefaultToolkit().getSystemClipboard();
        ImageIcon img = (ImageIcon) lb_code_img.getIcon();
        ImgCopied ic =  new ImgCopied(img.getImage());
        cb.setContents(ic, null);
        Principal.util.showDialog(rootPane, "La imagen se guardo en el portapapeles", "Imagen copiada", INFORMATION_MESSAGE);
        //searchImg();
    }//GEN-LAST:event_btn_new_copyimgActionPerformed

    private void btn_new_codebar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_new_codebar1ActionPerformed
        //generarCode();
    }//GEN-LAST:event_btn_new_codebar1ActionPerformed

    private void txt_new_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_new_totalActionPerformed
        
    }//GEN-LAST:event_txt_new_totalActionPerformed

    private void txt_new_totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_new_totalKeyTyped
         keyTypedOnlyNum(evt); 
    }//GEN-LAST:event_txt_new_totalKeyTyped

    private void txt_new_priceunitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_new_priceunitKeyTyped
        keyTypedOnlyNum(evt); 
    }//GEN-LAST:event_txt_new_priceunitKeyTyped

    private void txt_new_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_new_priceKeyTyped
        keyTypedOnlyNum(evt); 
    }//GEN-LAST:event_txt_new_priceKeyTyped

    private void txt_new_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_new_nameKeyTyped
       keyTypedTxt(evt);
    }//GEN-LAST:event_txt_new_nameKeyTyped

    private void txt_new_invimaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_new_invimaKeyTyped
        keyTypedTxt(evt);
    }//GEN-LAST:event_txt_new_invimaKeyTyped

    private void txt_new_distributorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_new_distributorKeyTyped
        keyTypedTxt(evt);
    }//GEN-LAST:event_txt_new_distributorKeyTyped

    private void txt_new_lotKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_new_lotKeyTyped
        keyTypedTxt(evt);
    }//GEN-LAST:event_txt_new_lotKeyTyped

    private void btn_new_edit_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_new_edit_infoActionPerformed
        enabledTextFields(true);
        enabledButtons(false);
        lb_code_img.setIcon(null);
    }//GEN-LAST:event_btn_new_edit_infoActionPerformed

    private void btn_new_clean_fieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_new_clean_fieldsActionPerformed
        txt_new_name.setText("");
        txt_new_distributor.setText("");
        txt_new_invima.setText("");
        txt_new_lot.setText("");
        txt_new_price.setText("");
        txt_new_priceunit.setText("");
        txt_new_total.setText("");
        dc_new_expiration_date.setDate(null);
        cb_new_duration.setSelectedIndex(0);
        cb_new_unit.setSelectedIndex(0);
        lb_code_img.setIcon(null);
        
        //Principal.util.getDataApi(this, "users-app/1");//Envia los datos a la api
        //Map<String, String> map =  new HashMap<>();
        //map.put("sp_name", "Especialidad 2");
        //Principal.util.sendDataApiEx(this, "specialtys",map);//Envia los datos a la api
        
    }//GEN-LAST:event_btn_new_clean_fieldsActionPerformed

    private void txt_new_trademarkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_new_trademarkKeyTyped
        keyTypedTxt(evt);
    }//GEN-LAST:event_txt_new_trademarkKeyTyped

    /**
     * Convierte texto minuscula a mayuscula
     * @param evt
     */
    public void keyTypedTxt(KeyEvent evt){
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar) && Character.isLetter(keyChar)) {
          evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }
    /**
     * Verifica que solo entren numeros
     * @param evt
     */
    public void keyTypedOnlyNum(KeyEvent evt){
        char c=evt.getKeyChar(); 
          if(Character.isLetter(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
              System.out.println("Ingresa Solo Numeros"); 
          } 
    }
    
    /**
     * Genera codigo de barras dependiendo del tipo de elemto que se ingrese previamente
     * @param art
     */
    public void generarCode(Articles art){
        String barCodeStr = Principal.util.getIntForCodebar(art, "3-1");
        jTextField1.setEnabled(false);
        jTextField1.setText(barCodeStr);
        
        Barcode barcode = null;
        try {
            barcode = BarcodeFactory.createCode128(barCodeStr);
        } catch (Exception e) {
        }
        barcode.setDrawingText(true);
        barcode.setBarWidth(2);
        barcode.setBarHeight(60);
        
        //pintando imagen
        BufferedImage img =  new BufferedImage(420, 110, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = (Graphics2D) img.getGraphics();
        
        try {
            barcode.draw(g, 5, 20);
        } catch (Exception e) {
        }
        //Creamos icono a partir de imagen
        ImageIcon icon =  new ImageIcon(img);
        lb_code_img.setIcon(icon);
        Date dateNow =  new Date();
        LocalDate localDate = LocalDate.now();
        System.out.println(DateTimeFormatter.ofPattern("yyy/MM/dd").format(localDate));
        //System.out.println(new Date().getTime());
    }
    
    public void enabledTextFields(boolean flag){
        txt_new_name.setEnabled(flag);
        txt_new_distributor.setEnabled(flag);
        txt_new_invima.setEnabled(flag);
        txt_new_lot.setEnabled(flag);
        txt_new_price.setEnabled(flag);
        txt_new_priceunit.setEnabled(flag);
        txt_new_total.setEnabled(flag);
        txt_new_trademark.setEnabled(flag);
        dc_new_expiration_date.setEnabled(flag);
        cb_new_duration.setEnabled(flag);
        cb_new_unit.setEnabled(flag);
        btn_new_codebar.setEnabled(flag);
        btn_new_clean_fields.setEnabled(flag);
    }
    public void enabledButtons(boolean flag){
        btn_new_copyimg.setEnabled(flag);
        btn_save_img.setEnabled(flag);
        btn_print_code.setEnabled(flag);
        btn_save_new_article.setEnabled(flag);
    
    }
    
    public String guardarImg(File file, byte[] byteImg){
        String res = null;
        //byte[] byteImg  = new byte[width*heigth];
        try {
            FileOutputStream entrada =  new FileOutputStream(file);
            entrada.write(byteImg);
            res = "La imagen se ha guardaro";
        } catch (Exception e) {
        }
        return res;
    }
    
    public void searchImg(){
        JFileChooser jfc =  new JFileChooser();
        jfc.showSaveDialog(this);
        File file = jfc.getSelectedFile();
        
        String filename = file.getAbsolutePath();
        System.out.println(filename);
        ImageIcon ic =  new ImageIcon(filename);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_new_clean_fields;
    private javax.swing.JButton btn_new_codebar;
    private javax.swing.JButton btn_new_codebar1;
    private javax.swing.JButton btn_new_copyimg;
    private javax.swing.JButton btn_new_edit_info;
    private javax.swing.JButton btn_print_code;
    private javax.swing.JButton btn_save_img;
    private javax.swing.JButton btn_save_new_article;
    private javax.swing.JComboBox<String> cb_new_duration;
    private javax.swing.JComboBox<String> cb_new_unit;
    private com.toedter.calendar.JDateChooser dc_new_expiration_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb_code_img;
    private javax.swing.JTextField txt_new_distributor;
    private javax.swing.JTextField txt_new_invima;
    private javax.swing.JTextField txt_new_lot;
    private javax.swing.JTextField txt_new_name;
    private javax.swing.JTextField txt_new_price;
    private javax.swing.JTextField txt_new_priceunit;
    private javax.swing.JTextField txt_new_total;
    private javax.swing.JTextField txt_new_trademark;
    // End of variables declaration//GEN-END:variables


}
