/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventarios_cbd;

import Utils.Utils;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;

/**
 *
 * @author Sebastian
 */
public class Principal extends javax.swing.JFrame {

    InputArticle na;
    
    public static Utils util;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        dp_principal.setBounds(this.getBounds());
        util = new Utils();
        
    }
    
    public void getDataInfoOffice(){
        util.sendDataApi("", this);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp_principal = new javax.swing.JDesktopPane();
        jp_info = new javax.swing.JPanel();
        lb_namesuer = new javax.swing.JLabel();
        lb_namecenter = new javax.swing.JLabel();
        lb_namerol = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        m_new = new javax.swing.JMenu();
        mi_new_article = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Sistema de inventarios"); // NOI18N

        dp_principal.setAutoscrolls(true);
        dp_principal.setRequestFocusEnabled(false);

        lb_namesuer.setText("Nombre usuario");

        lb_namecenter.setText("Centro");

        lb_namerol.setText("Rol");

        javax.swing.GroupLayout jp_infoLayout = new javax.swing.GroupLayout(jp_info);
        jp_info.setLayout(jp_infoLayout);
        jp_infoLayout.setHorizontalGroup(
            jp_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_namesuer)
                .addGap(180, 180, 180)
                .addComponent(lb_namecenter)
                .addGap(294, 294, 294)
                .addComponent(lb_namerol)
                .addContainerGap(549, Short.MAX_VALUE))
        );
        jp_infoLayout.setVerticalGroup(
            jp_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_namesuer)
                    .addComponent(lb_namecenter)
                    .addComponent(lb_namerol))
                .addContainerGap())
        );

        dp_principal.setLayer(jp_info, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dp_principalLayout = new javax.swing.GroupLayout(dp_principal);
        dp_principal.setLayout(dp_principalLayout);
        dp_principalLayout.setHorizontalGroup(
            dp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dp_principalLayout.setVerticalGroup(
            dp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dp_principalLayout.createSequentialGroup()
                .addComponent(jp_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 624, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        m_new.setText("Ingresar");

        mi_new_article.setText(" Articulo");
        mi_new_article.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_new_articleActionPerformed(evt);
            }
        });
        m_new.add(mi_new_article);

        jMenuBar1.add(m_new);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_new_articleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_new_articleActionPerformed
        na =  new InputArticle();
        dp_principal.add(na);
        na.setVisible(true);
    }//GEN-LAST:event_mi_new_articleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dp_principal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jp_info;
    private javax.swing.JLabel lb_namecenter;
    private javax.swing.JLabel lb_namerol;
    private javax.swing.JLabel lb_namesuer;
    private javax.swing.JMenu m_new;
    private javax.swing.JMenuItem mi_new_article;
    // End of variables declaration//GEN-END:variables
}
